docs/ingestion/open-telemetry.md

Added traces ingestion

---

docs/benchmarks/benchmark-runbook.md

This adds a runbook for performing benchmark tests on SigLens and the same tests on ClickHouse

Benchmark runbook

---

docs/installation/git.md

removed install script

---

docs/alerts.md
docs/cluster-health.md
docs/dashboards.md
docs/installation/docker.md
docs/installation/git.md
docs/introduction.md
docs/log-query-builder.md
docs/searching-logs.md
src/css/custom.css

* Git page Changes
* Docker Page Changes
* Introduction Changes
* Embedded Youtube Videos

Docs changes (#37)

---

docs/instrument-traces/go-app.md

This cleans up the tutorial for adding instrumentation to a Go app

Clean go docs

---

docs/instrument-traces/python-app.md

This gives examples for how to auto-instrument a Flask and Django app, as well as where to look to instrument Python apps written with different frameworks.

Simplify instrumenting a Python app

---

docs/benchmarks/nyc-taxi-benchmark-runbook.md

Adds the procedure for benchmarking Elasticsearch

Elasticsearch runbook

---

docs/log-ingestion/beats/filebeat-elasticsearch.md
docs/log-ingestion/beats/metricbeat-elasticsearch.md
docs/log-ingestion/fluentd/fluentd-elasticsearch.md
docs/log-ingestion/fluentd/fluentd-splunk.md
docs/log-ingestion/logstash/logstash-elasticsearch.md
docs/log-ingestion/logstash/logstash-splunk.md

- Changed some spell errors and add some new commands that might be required during the installation process of Ingestion Agents.

Ingestion Document Fixes

---

docs/log-ingestion/filebeat.md
docs/log-ingestion/fluentd.md
docs/log-ingestion/logstash.md
docs/log-ingestion/vector.md

- Modified the ingest configs so that the sample data `2kevents.json` will be ingested in the proper format.
- The format is similar to the data that is ingested if the ingestion command is run given on the contributing guide.

fix: Ingest Sample data in proper format.

---

docs/log-ingestion/filebeat.md
docs/log-ingestion/logstash.md
docs/log-ingestion/vector.md
docs/migration/datadog/vector.md
docs/migration/gcloud/vector.md
docs/migration/splunk/vector.md

* doc changes
* change baseurl for netlify
* add title
* typo fix
* Revert "change baseurl for netlify"
This reverts commit ed4d2a75c9ff413ecdce0a650ec602036a41c3b9.
* update docs
* update docs
* rename/delete unused files
* fix broken links
* typo fix
* update docs
* update docs
* update ingestion docs
* update docs
* update docs
* update docs
* updatedocs
* update docs
* update docs
* update docs
* update docs
* update docs
* update docs
* update docs
* update docs
* update docs
* update docs
* update docs
* update docs
* Update docs
---------
Co-authored-by: venkateshamatam <>

Docs Release

---

docs/log-ingestion/fluentd.md
docs/log-ingestion/logstash.md
docs/metric-ingestion/vector-metrics.md
docs/migration/gcloud/vector.md
docs/migration/splunk/fluentd.md
docs/migration/splunk/vector.md

Updates documentation to match changes from https://github.com/siglens/siglens/pull/672

Remove /splunk from the url

---

docs/searching-logs.md

- The Supported Commands were added as a new section under `Searching Logs` Page.

feat: added supported SPL commands reference

---

docs/spl-docs/makemv-command.md
docs/spl-docs/transaction-command.md
sidebars.js

- Added SPL doc for commands: `transaction` and `makemv`

feat: Added SPL doc for commands: transaction / makemv

---

docs/spl-docs/top-command.md
sidebars.js

- Added SPL doc for `top` command.

feat: Added SPL doc for Top command

---

docs/spl-docs/common-usecases.md
docs/spl-docs/eval-command.md
docs/spl-docs/evaluation-functions/comparison-conditional-functions.md
docs/spl-docs/fillnull-command.md
docs/spl-docs/splunk-commands.md
sidebars.js

- Added SPL documentation for command: fillnull and eval functions: null(), nullif()
- Also added the related use-cases to common use-cases page.

feat: Added SPL documentation for command: fillnull and eval functions: null(), nullif()

---

docs/spl-docs/evaluation-functions/multivalue-functions.md
docs/spl-docs/evaluation-functions/time-functions.md

time functions - https://docs.splunk.com/Documentation/SCS/current/SearchReference/DateandTimeFunctions#relative_time.28.26lt.3Btime.26gt.3B.2C.26lt.3Bspecifier.26gt.3B.29
multivalue eval functions - https://docs.splunk.com/Documentation/SCS/current/SearchReference/MultivalueEvalFunctions

Add docs for all multi-value commands and relative_time

---

docs/spl-docs/common-usecases.md
docs/spl-docs/inputlookup-command.md
docs/spl-docs/splunk-commands.md
sidebars.js

Added SPL documentation for inputlookup.
Also added the related use-cases to common use-cases page.

SPL documentation for InputLookup command

---

docusaurus.config.js

add link for playground server

---

docs/log-ingestion/fluent-bit.md
sidebars.js

- Fluent-bit Ingestion through Elastic Search ingest interface.

fluent-bit ingestion config

---

docs/spl-docs/aggregate-functions/agg-functions.md

Added documentation for [percentile](https://help.splunk.com/en/splunk-enterprise/search/spl-search-reference/9.4/statistical-and-charting-functions/aggregate-functions#ariaid-title13) and [median](https://help.splunk.com/en/splunk-enterprise/search/spl-search-reference/9.4/statistical-and-charting-functions/aggregate-functions#ariaid-title10)

added docs for percentile and median

---

docs/spl-docs/evaluation-functions/multivalue-functions.md

Add docs for mvzip
